**Импорт numpy и создание массивов**

In [16]:
import numpy as np

array1= np.arange(1,10,0.5) # создала массив от 1 до 10 с шагом 0.5 с помощью функции arange
print(array)
array2 = np.ones((1, 18)) # создала массив 1 размера 1 на 18 с помощью функции ones
print(array2)
print("Тип данных второго массива: ", array2.dtype)
array_twodim = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # создала двумерный массив
print(array_twodim)
print("Форма двумерного массива: ", array_twodim.shape)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Тип данных второго массива:  float64
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма двумерного массива:  (3, 4)


**Примеры индексирования и срезов**

In [20]:
print("Первый элемент первого массива: ", array[1]) # получила первый элемент первого массива
print("Четвёртый, пятый и шестой элементы первого массива: ", array[3:6]) # получила подмасссив с помощью среза с 3 до 6(не включительно) индексов
print("Перевёрнутый первый массив: ", array1[::-1]) # получила подмасссив с помощью срез первого массива в обраном порядке
print("Четвёртый элемент во второй строке", array_twodim[1, 3]) # получила элемент двумерного массива с индексами 1, 3
for element in array_twodim.flat: # вывод массива, индексы элементов изменены с помощью итерратора flat
    print(element)

Первый элемент первого массива:  1.5
Четвёртый, пятый и шестой элементы первого массива:  [2.5 3.  3.5]
Перевёрнутый первый массив:  [9.5 9.  8.5 8.  7.5 7.  6.5 6.  5.5 5.  4.5 4.  3.5 3.  2.5 2.  1.5 1. ]
Четвёртый элемент во второй строке 8
1
2
3
4
5
6
7
8
9
10
11
12


**Примеры векторных операций и базовых статистик**

In [27]:
array_sum = array - array2 # вычла из массива array массив array2
print(array_sum)
print(array_twodim.min(axis=1)) # нашла минимальный столбец в двумерном массиве 
array3 = array2 / array # 
print(array3)
print(array_twodim[1].mean()) # нашла среднее значение элементов второй строки двумерного массива

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]]
[1 5 9]
[[1.         0.66666667 0.5        0.4        0.33333333 0.28571429
  0.25       0.22222222 0.2        0.18181818 0.16666667 0.15384615
  0.14285714 0.13333333 0.125      0.11764706 0.11111111 0.10526316]]
6.5
